language: python
python:
  - "3.6"
  - "3.7"
dist: xenial

fast_finish: true

branches:
  only:
    - master

before_install:
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - export PATH="$HOME/.poetry/bin:$PATH"
install:
  - poetry install -v
script:
  - poetry run invoke acceptance
  - poetry run pytest tests
